//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:09:05 PM PST 
//


package partnerIntg.com.good.xmlprocess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Purchase Order Header Data
 * 
 * <p>Java class for poHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="poHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poDetails" type="{}poDetailsType"/>
 *         &lt;element name="SoldToCustomer" type="{}AddressDetailsType"/>
 *         &lt;element name="BillToCustomer" type="{}AddressDetailsType" minOccurs="0"/>
 *         &lt;element name="ShipToCustomer" type="{}AddressDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "poHeaderType", propOrder = {
    "poDetails",
    "soldToCustomer",
    "billToCustomer",
    "shipToCustomer"
})
public class PoHeaderType {

    @XmlElement(required = true)
    protected PoDetailsType poDetails;
    @XmlElement(name = "SoldToCustomer", required = true)
    protected AddressDetailsType soldToCustomer;
    @XmlElement(name = "BillToCustomer")
    protected AddressDetailsType billToCustomer;
    @XmlElement(name = "ShipToCustomer", required = true)
    protected AddressDetailsType shipToCustomer;

    /**
     * Gets the value of the poDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PoDetailsType }
     *     
     */
    public PoDetailsType getPoDetails() {
        return poDetails;
    }

    /**
     * Sets the value of the poDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoDetailsType }
     *     
     */
    public void setPoDetails(PoDetailsType value) {
        this.poDetails = value;
    }

    /**
     * Gets the value of the soldToCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDetailsType }
     *     
     */
    public AddressDetailsType getSoldToCustomer() {
        return soldToCustomer;
    }

    /**
     * Sets the value of the soldToCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDetailsType }
     *     
     */
    public void setSoldToCustomer(AddressDetailsType value) {
        this.soldToCustomer = value;
    }

    /**
     * Gets the value of the billToCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDetailsType }
     *     
     */
    public AddressDetailsType getBillToCustomer() {
        return billToCustomer;
    }

    /**
     * Sets the value of the billToCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDetailsType }
     *     
     */
    public void setBillToCustomer(AddressDetailsType value) {
        this.billToCustomer = value;
    }

    /**
     * Gets the value of the shipToCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link AddressDetailsType }
     *     
     */
    public AddressDetailsType getShipToCustomer() {
        return shipToCustomer;
    }

    /**
     * Sets the value of the shipToCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressDetailsType }
     *     
     */
    public void setShipToCustomer(AddressDetailsType value) {
        this.shipToCustomer = value;
    }

}
