//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.13 at 12:09:05 PM PST 
//


package partnerIntg.com.good.xmlprocess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchaseOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="poHeader" type="{}poHeaderType"/>
 *         &lt;element name="items" type="{}ItemsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseOrderType", propOrder = {
    "poHeader",
    "items"
})
public class PurchaseOrderType {

    @XmlElement(required = true)
    protected PoHeaderType poHeader;
    @XmlElement(required = true)
    protected ItemsType items;

    /**
     * Gets the value of the poHeader property.
     * 
     * @return
     *     possible object is
     *     {@link partnerIntg.com.good.xmlprocess.PoHeaderType }
     *     
     */
    public PoHeaderType getPoHeader() {
        return poHeader;
    }

    /**
     * Sets the value of the poHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link partnerIntg.com.good.xmlprocess.PoHeaderType }
     *     
     */
    public void setPoHeader(PoHeaderType value) {
        this.poHeader = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link partnerIntg.com.good.xmlprocess.ItemsType }
     *     
     */
    public ItemsType getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link partnerIntg.com.good.xmlprocess.ItemsType }
     *     
     */
    public void setItems(ItemsType value) {
        this.items = value;
    }

}
